config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("edurock.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("edurock.pages.urls", namespace="pages")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

edurock/pages/urls.py
from django.urls import path
from pages.views import (root_page_view, dynamic_pages_view)

app_name = 'pages'

urlpatterns = [
    path('', root_page_view, name="index"),
    path('<str:template_name>/', dynamic_pages_view, name='dynamic_pages')
]

edurock/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

edurock/pages/models.py
from django.db import models

# Create your models here.

edurock/users/models.py
from typing import ClassVar

from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.db.models import EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for edurock.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore[assignment]

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects: ClassVar[UserManager] = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

edurock/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

edurock/pages/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.template import TemplateDoesNotExist

# @login_required
def root_page_view(request):
    try:
        return render(request, 'pages/maintenance.html')
    except TemplateDoesNotExist:
        return render(request, 'pages/error.html')


# @login_required
def dynamic_pages_view(request, template_name):
    try:
        return render(request, 'pages/maintenance.html')
        # return render(request, f'pages/{template_name}.html')
    except TemplateDoesNotExist:
        return render(request, f'pages/error.html')

edurock/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from edurock.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

edurock/templates/layouts/admin.html
{% extends 'base.html' %}

{% load static i18n %}

{% block title %}{% endblock %}

{% block extra_css %} {% endblock %}

{% block body_attribute %}{% endblock %}

{% block preloader %}

{% endblock %}

{% block content %}
  {% include 'partials/theme-switch.html' %}

  <main class="main_wrapper overflow-hidden">

    {% include 'partials/top-banner-2.html' %}

    {% include 'partials/navbar-2.html' %}

    {% include 'partials/mobile-menu.html' %}

    <div>
      <div class="theme__shadow__circle"></div>
      <div class="theme__shadow__circle shadow__right"></div>
    </div>

    <div class="dashboardarea sp_bottom_100">
      <div class="container-fluid full__width__padding">
        <div class="row">
          <div class="col-xl-12">
            <div class="dashboardarea__wraper">
              <div class="dashboardarea__img">
                <div class="dashboardarea__inner admin__dashboard__inner">
                  <div class="dashboardarea__left">
                    <div class="dashboardarea__left__img">
                      <img  src="{% static 'img/dashbord/dashbord__2.jpg' %}" alt="">
                    </div>
                    <div class="dashboardarea__left__content">
                      <h5>Hello</h5>
                      <h4>Michle Obema</h4>
                    </div>
                  </div>
                  <div class="dashboardarea__star">
                    <i class="icofont-star"></i>
                    <i class="icofont-star"></i>
                    <i class="icofont-star"></i>
                    <i class="icofont-star"></i>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                         viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                         stroke-linecap="round" stroke-linejoin="round" class="feather feather-star">
                      <polygon
                        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2">
                      </polygon>
                    </svg>
                    <span>4.0 (120 Reviews)</span>
                  </div>
                  <div class="dashboardarea__right">
                    <div class="dashboardarea__right__button">
                      <a class="default__button" href="{% url 'pages:dynamic_pages' template_name='create-course' %}">Create a New Course
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                             viewBox="0 0 24 24" fill="none" stroke="currentColor"
                             stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="feather feather-arrow-right">
                          <line x1="5" y1="12" x2="19" y2="12"></line>
                          <polyline points="12 5 19 12 12 19"></polyline>
                        </svg>
                      </a>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="dashboard">
        <div class="container-fluid full__width__padding">
          <div class="row">

            {% include 'partials/admin-sidebar.html' %}

            {% block page_content %}{% endblock %}

          </div>
        </div>
      </div>
    </div>

    {% include 'partials/footer-2.html' %}
  </main>

{% endblock %}

{% block extra_javascript %} {% endblock %}

edurock/templates/layouts/instructor.html
{% extends 'base.html' %}

{% load static i18n %}

{% block title %}{% endblock %}

{% block extra_css %} {% endblock %}

{% block body_attribute %}{% endblock %}

{% block preloader %}

{% endblock %}

{% block content %}
  {% include 'partials/theme-switch.html' %}

  <main class="main_wrapper overflow-hidden">

    {% include 'partials/top-banner-2.html' %}

    {% include 'partials/navbar-2.html' %}

    {% include 'partials/mobile-menu.html' %}

    <div>
      <div class="theme__shadow__circle"></div>
      <div class="theme__shadow__circle shadow__right"></div>
    </div>

    <div class="dashboardarea sp_bottom_100">

      <div class="container-fluid full__width__padding">
        <div class="row">
          <div class="col-xl-12">
            <div class="dashboardarea__wraper">
              <div class="dashboardarea__img">
                <div class="dashboardarea__inner">
                  <div class="dashboardarea__left">
                    <div class="dashboardarea__left__img">
                      <img  src="{% static 'img/dashbord/dashbord__2.jpg' %}" alt="">
                    </div>
                    <div class="dashboardarea__left__content">
                      <h5>Hello</h5>
                      <h4>Michle Obema</h4>
                    </div>
                  </div>
                  <div class="dashboardarea__star">
                    <i class="icofont-star"></i>
                    <i class="icofont-star"></i>
                    <i class="icofont-star"></i>
                    <i class="icofont-star"></i>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="feather feather-star">
                      <polygon
                        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
                    </svg>
                    <span>4.0 (120 Reviews)</span>
                  </div>
                  <div class="dashboardarea__right">
                    <div class="dashboardarea__right__button">
                      <a class="default__button" href="{% url 'pages:dynamic_pages' template_name='create-course' %}">Create a New Course
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="feather feather-arrow-right">
                          <line x1="5" y1="12" x2="19" y2="12"></line>
                          <polyline points="12 5 19 12 12 19"></polyline>
                        </svg>
                      </a>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="dashboard">
        <div class="container-fluid full__width__padding">
          <div class="row">

            {% include 'partials/instructor-sidebar.html' %}

            {% block page_content %}{% endblock %}

          </div>
        </div>
      </div>
    </div>

    {% include 'partials/footer-2.html' %}
  </main>

{% endblock %}

{% block extra_javascript %} {% endblock %}

edurock/templates/layouts/student.html
{% extends 'base.html' %}

{% load static i18n %}

{% block title %}{% endblock %}

{% block extra_css %} {% endblock %}

{% block body_attribute %}{% endblock %}

{% block preloader %}

{% endblock %}

{% block content %}
  {% include 'partials/theme-switch.html' %}

  <main class="main_wrapper overflow-hidden">

    {% include 'partials/top-banner-2.html' %}

    {% include 'partials/navbar-2.html' %}

    {% include 'partials/mobile-menu.html' %}

    <div>
      <div class="theme__shadow__circle"></div>
      <div class="theme__shadow__circle shadow__right"></div>
    </div>

    <div class="dashboardarea sp_bottom_100">

      <div class="container-fluid full__width__padding">
        <div class="row">
          <div class="col-xl-12">
            <div class="dashboardarea__wraper">
              <div class="dashboardarea__img">
                <div class="dashboardarea__inner student__dashboard__inner">
                  <div class="dashboardarea__left">
                    <div class="dashboardarea__left__img">
                      <img  src="{% static 'img/teacher/teacher__2.png' %}" alt="">
                    </div>
                    <div class="dashboardarea__left__content">
                      <h4>Dond Tond</h4>
                      <ul>
                        <li>
                          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                               stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                               class="feather feather-book-open">
                            <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path>
                            <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path>
                          </svg>
                          9 Courses Enroled
                        </li>
                        <li>
                          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                               stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                               class="feather feather-award">
                            <circle cx="12" cy="8" r="7"></circle>
                            <polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline>
                          </svg>
                          8 Certificate
                        </li>
                      </ul>

                    </div>
                  </div>
                  <div class="dashboardarea__right">
                    <div class="dashboardarea__right__button">
                      <a class="default__button" href="{% url 'pages:dynamic_pages' template_name='create-course' %}">Enroll A New Course
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="feather feather-arrow-right">
                          <line x1="5" y1="12" x2="19" y2="12"></line>
                          <polyline points="12 5 19 12 12 19"></polyline>
                        </svg>
                      </a>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="dashboard">
        <div class="container-fluid full__width__padding">
          <div class="row">

            {% include 'partials/student-sidebar.html' %}

            {% block page_content %}{% endblock %}

          </div>
        </div>
      </div>
    </div>

    {% include 'partials/footer-2.html' %}
  </main>

{% endblock %}

{% block extra_javascript %} {% endblock %}

edurock/templates/pages/error-dark.html
{% extends 'base.html' %}

{% load static i18n %}

{% block html_attribute %}class="no-js is_dark"{% endblock html_attribute %}
{% block body_attribute %}class="body__wrapper is_dark"{% endblock body_attribute %}

{% block title %}Error Dark{% endblock %}

{% block extra_css %} {% endblock %}

{% block preloader %}

{% endblock %}

{% block content %}
{% include 'partials/theme-switch.html' %}

<main class="main_wrapper overflow-hidden">

    <!-- topbar__section__stert -->
    {% include 'partials/top-banner-2.html' %}
    <!-- topbar__section__end -->

    <!-- headar section start -->
    {% include 'partials/navbar-2.html' %}
    <!-- header section end -->

    <!-- Mobile Menu Start Here -->
    {% include 'partials/mobile-menu.html' %}
    <!-- Mobile Menu end Here -->

    <!-- theme fixed shadow -->
    <div>
        <div class="theme__shadow__circle"></div>
        <div class="theme__shadow__circle shadow__right"></div>
    </div>
    <!-- theme fixed shadow -->
    <!-- breadcrumbarea__section__start -->

    <div class="breadcrumbarea">

        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="breadcrumb__content__wraper" ">
                        <div class="breadcrumb__title">
                            <h2 class="heading">Contact Page</h2>
                        </div>
                        <div class="breadcrumb__inner">
                            <ul>
                                <li><a href="{% url 'pages:dynamic_pages' template_name='index' %}">Home</a></li>
                                <li>Contact page</li>
                            </ul>
                        </div>
                    </div>



                </div>
            </div>
        </div>

        <div class="shape__icon__2">
            <img  class=" shape__icon__img shape__icon__img__1" src="{% static 'img/herobanner/herobanner__1.png' %}"
                alt="photo">
            <img  class=" shape__icon__img shape__icon__img__2" src="{% static 'img/herobanner/herobanner__2.png' %}"
                alt="photo">
            <img  class=" shape__icon__img shape__icon__img__3" src="{% static 'img/herobanner/herobanner__3.png' %}"
                alt="photo">
            <img  class=" shape__icon__img shape__icon__img__4" src="{% static 'img/herobanner/herobanner__5.png' %}"
                alt="photo">
        </div>

    </div>
    <!-- breadcrumbarea__section__end-->

    <!-- error__section__start -->
    <div class="errorarea sp_top_100 sp_bottom_100">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-10 col-sm-12 col-12 m-auto">
                    <div class="errorarea__inner" ">
                        <div class="error__img">
                            <img  src="{% static 'img/icon/error__1.png' %}" alt="error">
                        </div>
                        <div class="error__text">
                            <h3>Oops... It looks like you ‘re lost !</h3>
                            <p>Oops! The page you are looking for does not exist. It might have been moved or deleted
                            </p>
                        </div>
                        <div class="error__button">
                            <a class="default__button" href="#">Back To Home
                                <i class="icofont-simple-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- error__section__end -->


    <!-- footer__section__start -->
    <div class="footerarea">
        <div class="container">
            <div class="footerarea__newsletter__wraper">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12" ">
                        <div class="footerarea__text">
                            <h3>Still You Need Our <span>Support</span> ?</h3>
                            <p>Don’t wait make a smart & logical quote here. Its pretty easy.</p>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12" ">
                        <div class="footerarea__newsletter">
                            <div class="footerarea__newsletter__input">
                                <form action="#">
                                    <input type="text" placeholder="Enter your email here">
                                    <div class="footerarea__newsletter__button">
                                        <button type="submit" class="subscribe__btn">Subscribe Now</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footerarea__wrapper footerarea__wrapper__2">
                <div class="row">
                    <div class="col-xl-4 col-lg-4 col-sm-12 col-md-12" ">
                        <div class="footerarea__inner footerarea__about__us">
                            <div class="footerarea__heading">
                                <h3>About us</h3>
                            </div>
                            <div class="footerarea__content">
                                <p>orporate clients and leisure travelers has been relying on Groundlink for dependable
                                    safe, and professional chauffeured car end service in major cities across World.</p>
                            </div>
                            <div class="foter__bottom__text">
                                <div class="footer__bottom__icon">
                                    <i class="icofont-clock-time"></i>
                                </div>
                                <div class="footer__bottom__content">
                                    <h6>Opening Houres</h6>
                                    <span>Mon - Sat(8.00 - 6.00)</span>
                                    <span>Sunday - Closed</span>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-2 col-sm-6 col-md-6" ">
                        <div class="footerarea__inner">
                            <div class="footerarea__heading">
                                <h3>Usefull Links</h3>
                            </div>
                            <div class="footerarea__list">
                                <ul>
                                    <li>
                                        <a href="#">About Us</a>
                                    </li>
                                    <li>
                                        <a href="#">Teachers</a>
                                    </li>
                                    <li>
                                        <a href="#">Partner</a>
                                    </li>
                                    <li>
                                        <a href="#">Room-Details</a>
                                    </li>
                                    <li>
                                        <a href="#">Gallery</a>
                                    </li>
                                </ul>
                            </div>


                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-sm-6 col-md-6" ">
                        <div class="footerarea__inner footerarea__padding__left">
                            <div class="footerarea__heading">
                                <h3>Course</h3>
                            </div>
                            <div class="footerarea__list">
                                <ul>
                                    <li>
                                        <a href="#">Ui Ux Design</a>
                                    </li>
                                    <li>
                                        <a href="#">Web Development</a>
                                    </li>
                                    <li>
                                        <a href="#">Business Strategy</a>
                                    </li>
                                    <li>
                                        <a href="#">Softwere Development</a>
                                    </li>
                                    <li>
                                        <a href="#">Business English</a>
                                    </li>
                                </ul>
                            </div>


                        </div>
                    </div>

                    <div class="col-xl-3 col-lg-3 col-sm-12" ">
                        <div class="footerarea__right__wraper footerarea__inner">
                            <div class="footerarea__heading">
                                <h3>Recent Post</h3>
                            </div>
                            <div class="footerarea__right__list">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <div class="footerarea__right__img">
                                                <img  src="{% static 'img/footer/footer__1.png' %}" alt="footerphoto">
                                            </div>
                                            <div class="footerarea__right__content">
                                                <span>02 Apr 2024 </span>
                                                <h6>Best Your Business</h6>
                                            </div>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <div class="footerarea__right__img">
                                                <img  src="{% static 'img/footer/footer__2.png' %}" alt="footerphoto">
                                            </div>
                                            <div class="footerarea__right__content">
                                                <span>02 Apr 2024 </span>
                                                <h6>Keep Your Business</h6>
                                            </div>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <div class="footerarea__right__img">
                                                <img  src="{% static 'img/footer/footer__3.png' %}" alt="footerphoto">
                                            </div>
                                            <div class="footerarea__right__content">
                                                <span>02 Apr 2024 </span>
                                                <h6>Nice Your Business</h6>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footerarea__copyright__wrapper footerarea__copyright__wrapper__2">
                <div class="row">
                    <div class="col-xl-3 col-lg-3">
                        <div class="copyright__logo">
                            <a href="/"><img  src="{% static 'img/logo/logo_2.png' %}" alt="logo"></a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6">
                        <div class="footerarea__copyright__content footerarea__copyright__content__2">
                            <p>Copyright © <span>2024</span> by edurock. All Rights Reserved.</p>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3">
                        <div class="footerarea__icon footerarea__icon__2">
                            <ul>
                                <li><a href="//facebook.com"><i class="icofont-facebook"></i></a></li>
                                <li><a href="//twitter.com"><i class="icofont-twitter"></i></a></li>
                                <li><a href="//vimeo.com"><i class="icofont-vimeo"></i></a></li>
                                <li><a href="//linkedin.com"><i class="icofont-linkedin"></i></a></li>
                                <li><a href="//skype.com"><i class="icofont-skype"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- footer__section__end -->


</main>

{% endblock %}

{% block extra_javascript %} {% endblock %}

edurock/templates/users/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}


  {{ user.name }}


{% endblock title %}
{% block content %}
  <h1>
  
  
    {{ user.name }}
  
  
</h1>
<form class="form-horizontal"
      method="post"
      action="{% url 'users:update' %}">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn btn-primary">Update</button>
    </div>
  </div>
</form>
{% endblock content %}